### ISSUE TITLE
How do I check Pending Payment Status?

### ISSUE THREAD

**Issue by pratikbutani** [wangsun6/android-upi-payment#1]
Thanks for your code.

I have done transaction and its displaying message like `Payment Pending` and when I get back to app, Its displaying toast as Payment Cancelled. 

Is there any way to get status of that payment transaction.

**Comment by deorabanna1925** [comment]
How to resolve this error

`No virtual method getDialog()Lcom/google/android/material/bottomsheet/BottomSheetDialog; in class Lcom/wangsun/upi/payment/ui/UpiBottomSheet; or its super classes (declaration of 'com.wangsun.upi.payment.ui.UpiBottomSheet' appears in /data/app/co.careunit.main-1/base.apk:classes3.dex)`

**Comment by wangsun6** [comment]
@pratikbutani which UPI-app are you using for transaction??

**Comment by deorabanna1925** [comment]
App crashes everytime I call method payUPI()

**Comment by wangsun6** [comment]
@deorabanna1925 Are u implementing our library in app gradle file. Or are you opening directly the source file???

**Comment by deorabanna1925** [comment]
I tried after implementation in app gradle file but it crashes.

**Comment by wangsun6** [comment]
send snapshot of your implementation.

**Comment by pratikbutani** [comment]
> @pratikbutani which UPI-app are you using for transaction??

I am using G-Pay.

**Comment by deorabanna1925** [comment]
Actually this is working fine in an activity but app crashes when i call the same function `payUPI()` from a dialog inside a fragment.

Any Solution.....? 
![image](https://user-images.githubusercontent.com/32173870/71074318-104e2300-21a8-11ea-850c-9e9a2258fd81.png)

**Comment by wangsun6** [comment]
@deorabanna1925  i think it's because we show list of UpiApps in bottomSheetDialogFragment which extent from dialog. so may be whenever u call pay() function from dialog. it can't create dialog at the same time. So calling function from dialog is not possible.

**Comment by wangsun6** [comment]
@pratikbutani whenever the transaction is pending onSubmitted() method will be called.
But as i can see..this method will be never called. I made a small mistake in callback method. I will correct it and let you know.

**Comment by wangsun6** [comment]
@pratikbutani i have updated the code. Callback method onSubmitted() will be called whenever transaction is pending.
but if the result is pending then there is no way to know whether the transaction will be success or failed in future. So you need to be careful whenever this happen.

**Comment by pratikbutani** [comment]
> @pratikbutani i have updated the code. Callback method onSubmitted() will be called whenever transaction is pending.
> but if the result is pending then there is no way to know whether the transaction will be success or failed in future. So you need to be careful whenever this happen.

Thank you so much :)

**Comment by pratikbutani** [comment]
@deorabanna1925  Sorry but this issue is different than yours. Please file [new issue ](https://github.com/wangsun6/android-upi-payment/issues/new) with your questions.
